DROP DATABASE IF EXISTS cardsDB;
CREATE DATABASE cardsDB;
USE cardsDB;




CREATE TABLE card (
    id INT UNSIGNED AUTO_INCREMENT,
    fName VARCHAR(100),
    lName VARCHAR(100) NOT NULL,
    team VARCHAR (100) NOT NULL,
    manager VARCHAR(100) NOT NULL,
    price TINYINT NOT NULL,
    image VARCHAR(100) NOT NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_id PRIMARY KEY(id)
);